#!/bin/sh
# This is a generated file; do not edit or check into version control.
export "FLUTTER_ROOT=/Users/cagribas/development/flutter"
export "FLUTTER_APPLICATION_PATH=/Users/cagribas/AndroidStudioProjects/esp1 copy 2"
export "FLUTTER_TARGET=/Users/cagribas/AndroidStudioProjects/esp1 copy 2/lib/main.dart"
export "FLUTTER_BUILD_DIR=build"
export "SYMROOT=${SOURCE_ROOT}/../build/ios"
export "OTHER_LDFLAGS=$(inherited) -framework Flutter"
export "FLUTTER_FRAMEWORK_DIR=/Users/cagribas/development/flutter/bin/cache/artifacts/engine/ios"
export "FLUTTER_BUILD_NAME=0.1.5"
export "FLUTTER_BUILD_NUMBER=0.1.5"
export "DART_OBFUSCATION=false"
export "TRACK_WIDGET_CREATION=true"
export "TREE_SHAKE_ICONS=false"
export "PACKAGE_CONFIG=.packages"
